-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 10, 2024 at 08:25 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `entrepreneurclub`
--

-- --------------------------------------------------------

--
-- Table structure for table `entry`
--

CREATE TABLE `entry` (
  `SL_NO` int(11) NOT NULL,
  `Id` int(11) DEFAULT NULL,
  `Name` varchar(255) DEFAULT NULL,
  `StartupName` varchar(255) DEFAULT NULL,
  `StartupDomain` varchar(255) DEFAULT NULL,
  `BusinessModel` text DEFAULT NULL,
  `USP` text DEFAULT NULL,
  `TargetMarket` text DEFAULT NULL,
  `Revenue2020` int(11) DEFAULT NULL,
  `Revenue2021` int(11) DEFAULT NULL,
  `Revenue2022` int(11) DEFAULT NULL,
  `Revenue2023` int(11) DEFAULT NULL,
  `Expenses2023` int(11) DEFAULT NULL,
  `Profit` int(11) DEFAULT NULL,
  `PitchVideo` varchar(255) DEFAULT NULL,
  `Password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `entry`
--

INSERT INTO `entry` (`SL_NO`, `Id`, `Name`, `StartupName`, `StartupDomain`, `BusinessModel`, `USP`, `TargetMarket`, `Revenue2020`, `Revenue2021`, `Revenue2022`, `Revenue2023`, `Expenses2023`, `Profit`, `PitchVideo`, `Password`) VALUES
(1, 1, 'Nandini', 'CelestiaCharm Cosmetics', 'Skincare', 'Business model for cosmetic beauty products could involve a combination of selling directly to consumers, wholesale to retailers, or a mix of both. Consider exploring e-commerce, subscription models, or collaborating with beauty influencers for marketing. Additionally, you might offer personalized skincare consultations or incorporate sustainable and ethical practices to differentiate your brand. Analyze market trends and consumer preferences to tailor your business model to meet the demands of your target audience.', 'In the realm of cosmetic beauty, our brand, RadiantGlow Beauty Co., stands apart with an unwavering commitment to harnessing the power of nature. Our unique selling proposition lies in the exclusive use of premium natural ingredients, carefully selected to promote radiant and healthy skin.', '5. Diverse Demographics, Nature-Inspired Radiance, Transparency and Community Engagement', 225000, 350000, 500000, 800000, 280000, 65, 'http://localhost/pitch/WhatsApp Video 2024-01-07 at 00.14.42 (2).mp4', '$2y$10$DlSePh0obAr6OPdx5ehoRuxBFpZbl94FFiNfgwNqNrb7ZTKPog3Ym'),
(2, 1, 'Nandini', 'Summit Skincare', 'Skincare', 'Summit Skincare\'s business model revolves around a direct-to-consumer approach, primarily operating through an e-commerce platform. Our focus is on providing high-quality skincare products directly to customers via our online store. Emphasizing convenience and personalized care, we offer subscription options for regular product deliveries, ensuring that customers can seamlessly integrate our premium skincare solutions into their routines. Additionally, we explore collaborations with skincare professionals and influencers to enhance our brand visibility and credibility. ', '4. Summit Skincare\'s unique selling proposition (USP) lies in the convergence of premium quality, natural ingredients, and a commitment to individualized skincare experiences. Our products stand out by offering a harmonious blend of science-backed formulations and nature\'s bounty, providing customers with effective solutions that prioritize skin health and radiance.\r\n', 'Demographic Focus, Consumer Profile, Environmental Considerations , Personalization', 225000, 350000, 400000, 600000, 230000, 61, 'http://localhost/pitch/WhatsApp Video 2024-01-07 at 00.34.53 (1).mp4', '$2y$10$wU2gyoAlYW09IVTuEp20huLhXFMdw2DSWTvC3kEvQ9YqVVSec0Vi6'),
(3, 3, 'Savitri', 'GameVista', 'Gaming', 'Our business model can encompass various avenues. Whether through the sale of VR hardware, software, or subscriptions, catering to diverse applications like education, real estate, and social interactions. Consider offering consultancy services for businesses embracing VR, or delve into content creation, developing immersive experiences for a wide audience. Exploring partnerships and sponsorships can enhance your reach and market presence. By evaluating your target audience and industry trends, you can craft a comprehensive business model, possibly combining multiple revenue streams for a resilient and adaptable approach.', 'Distinguishing your VR startup in a competitive landscape can be achieved through a robust Unique Selling Proposition (USP). Position your venture as more than a gaming platform by emphasizing the versatility of your VR solutions. Showcase a diverse range of applications, from immersive educational experiences to real estate tours and seamless social interactions. Your USP should extend to providing high-quality, exclusive content that captivates users and keeps them engaged.', 'Consumers , Education Institution, Real estate Professionals', 225000, 423000, 520000, 600000, 175900, 68, 'http://localhost/pitch/WhatsApp Video 2024-01-07 at 12.46.28 (1).mp4', '$2y$10$G8wjP5kxAIBEvrl3aY0dp.zPztrNX7SRVgZ1YLBe9y5OjUVSZdKNu'),
(4, 2, 'Ranjitha', 'Vedantu', 'Education', 'Vedantu, being an online tutoring platform, typically follows a subscription or pay-per-class business model. Students often pay for access to live interactive classes, personalized learning plans, and other educational resources. The platform may also offer different subscription plans or charge fees based on the number of classes or specific subjects. Additionally, Vedantu may generate revenue through partnerships, collaborations, or other supplementary services within the education sector.', 'Vedantu stands out in the online education landscape through its distinctive live interactive tutoring model. The platform\'s unique selling proposition revolves around the dynamic engagement fostered by real-time, one-on-one or small group interactions between students and qualified educators. What sets Vedantu apart is its commitment to personalized learning plans, tailoring educational content to individual student needs for a more effective and targeted approach. ', 'Teaching approach , Convenience, Focus , Comprehensive solution', 357000, 528000, 700000, 900000, 320000, 64, 'http://localhost/pitch/WhatsApp Video 2024-01-07 at 12.57.56 (1).mp4', '$2y$10$IvbrqLvJAVofbD2XiDiMtuNr4kTh4TdpdeAKpm51MsQPepUKfhD8S'),
(5, 5, 'Monica', 'Dreambox learning', 'Education', 'DreamBox Learning typically operates on a subscription-based business model. Schools, districts, or individual users pay a fee to access the platform\'s educational resources and services. The subscription fee grants users access to the adaptive math curriculum, personalized learning features, progress tracking, and other tools aimed at improving math proficiency. This model allows DreamBox to generate revenue while providing an interactive and tailored learning experience for students.\r\n', 'DreamBox Learning\'s unique selling proposition lies in its adaptive learning platform. It uses intelligent algorithms to personalize the learning experience for each student, adjusting content based on individual strengths and areas that need improvement. The platform\'s engaging and interactive lessons, combined with real-time feedback and progress tracking, set it apart. This adaptability and focus on individualized learning contribute to a more effective and personalized educational experience, making it a standout choice for educators and students seeking a dynamic approach to math learning.', 'Education Market , Adaptive and Personalised , Specifically designed', 450000, 923000, 1200000, 1300000, 400000, 67, 'http://localhost/pitch/edu.mp4', '$2y$10$FQEn7IMDplm/xMuQLZb9GeiH3oAAPyQgh6WPlsy2S6Qxj1Ql74Tdi'),
(6, 3, 'Savitri', 'Kidaptive', 'Education', 'The business model involves offering educational technology solutions, particularly adaptive learning platforms for children. They may generate revenue through various channels, such as selling licenses to educational institutions, subscription-based models for individual users, or partnerships with schools and other educational organizations. \r\n', 'Kidaptive\'s unique selling proposition (USP) lies in its emphasis on personalized and adaptive learning for children. The company focuses on creating educational technology solutions that tailor the learning experience to each child\'s individual needs and learning style. This approach aims to enhance engagement and effectiveness by providing a more customized educational journey, setting Kidaptive apart in the edtech space.', 'Parents, Educators , Individual Consumers, Educational Institutions', 500000, 700000, 900000, 1000000, 350000, 65, 'http://localhost/pitch/edu1.mp4', '$2y$10$rSa2Ul9uqgdaaogLZr671.UuCOiopW4EL1IrD7.Xh8keeyDXmzz1W'),
(7, 4, 'Ganapriya', 'Gung The Palace', 'Food', 'Embark on a culinary journey with a business centered around Korean-style food. Establish a vibrant restaurant or cafe, immersing patrons in the rich flavors of authentic Korean cuisine. Elevate customer convenience by incorporating delivery and takeout services, ensuring that the essence of Korean flavors reaches homes across your region. Diversify your revenue streams by offering catering services for events and gatherings, showcasing the diverse and delectable range of Korean dishes. Alternatively, delve into the world of subscription boxes, curating and delivering handpicked Korean ingredients or meal kits to subscribers, enabling them to recreate the magic of Korean cooking at home. Extend your reach globally by venturing into online cooking classes, where enthusiasts can learn the art of crafting Korean delicacies from the comfort of their own kitchens.', 'Korean-style food business through a compelling Unique Selling Proposition (USP) that revolves around authenticity and an immersive dining experience. At the heart of your venture is a commitment to delivering the true essence of Korean cuisine, employing traditional recipes, genuine ingredients, and expert cooking techniques. Elevate the dining atmosphere by creating a cultural ambiance that transports patrons to Korea, weaving in elements of decor, music, and an overall experience that resonates with the rich tapestry of Korean culture. Unveil exclusive offerings, whether it be signature dishes or innovative culinary creations that seamlessly blend traditional flavors with a contemporary twist, establishing your establishment as a culinary destination like no other. ', 'Cultural Explores , Food enthusiasts , Health-Consicious', 550000, 1250000, 1600000, 1800000, 500000, 72, 'http://localhost/pitch/food.mp4', '$2y$10$vhXRbOmnHcJyMgflLMjIPuRFYbbw7iP8btnB71q8IIg8/ezd1W8.W'),
(8, 2, 'Ranjitha', 'Golden Chopsticks', 'Food', '3. To establish a successful Chinese restaurant startup, consider adopting a multifaceted business model. Prioritize a welcoming dine-in experience with a diverse menu to cater to traditional preferences. Capitalize on the growing demand for takeout and delivery services, emphasizing convenience for customers who prefer enjoying Chinese cuisine at home. Expand your revenue streams through catering services for events and parties. Leverage the digital landscape by developing an intuitive website and mobile app for online orders. Explore subscription services to cultivate customer loyalty and offer exclusive benefits. Collaborate with food delivery platforms to broaden your reach, and implement special events, promotions, and loyalty programs to attract and retain customers. Additionally, consider unique revenue streams such as branded merchandise or collaborations with local businesses. Regularly reassess and adapt your business model to stay responsive to market trends and customer preferences.\r\n', 'Our Chinese restaurant\'s success hinges on a distinctive Unique Selling Proposition (USP). Consider positioning your establishment as the epitome of authenticity, showcasing time-honored Chinese recipes, culinary techniques, and premium ingredients to deliver an unparalleled dining experience. Introduce signature dishes or innovative interpretations of classics, creating a culinary identity that sets you apart. Alternatively, emphasize health-conscious options, catering to dietary preferences with gluten-free or low-sodium offerings.', 'Demographics , Location, Culinary Preferences', 1200000, 1800000, 2000000, 2100000, 555000, 10, 'http://localhost/pitch/food1.mp4', '$2y$10$TUtZDCz0ueUTgA2iJo0I9OrzdvFMnaaucwZecNpN3VGIp.j0h76oa'),
(9, 3, 'Savitri', 'VillageVibe foods', 'Food', 'VillageVibe Foods aims to create an immersive experience around traditional non-vegetarian dishes. Our business model revolves around providing a charming dine-in atmosphere, allowing customers to savor authentic village flavors in a rustic setting. For those who prefer enjoying our offerings at home, we offer a seamless takeout and delivery service. Additionally, we extend our reach through catering services, bringing our unique village-style cuisine to events and gatherings. To cater to the growing demand for convenience, we also offer subscription boxes, providing curated ingredients and recipes for customers to recreate the village food experience in their own homes. Embracing the digital era, our online platform facilitates easy ordering, reservations, and virtual sharing of the VillageVibe Foods experience. This comprehensive approach ensures that we cater to various preferences while staying true to our commitment to delivering genuine and delightful non-vegetarian delights with a village charm.', '4. VillageVibe Foods distinguishes itself through a unique combination of authentic flavors, rustic ambiance, and a commitment to preserving traditional non-vegetarian recipes. Our focus on sourcing high-quality, local ingredients ensures an unparalleled taste that transports customers to the heart of a village kitchen. The immersive dine-in experience captures the essence of village life, creating a distinctive atmosphere that sets us apart. Whether enjoying our offerings in-house, through takeout, or with our subscription boxes, customers can count on the genuine and delightful VillageVibe experience. Our dedication to bridging the gap between tradition and modern convenience, coupled with a passion for preserving the rich heritage of non-vegetarian cuisine, establishes VillageVibe Foods as a standout destination for those seeking an authentic and memorable culinary journey.\r\n', 'Cultural Explores, Event Organizers and Hosts , Convenience Seekers', 253700, 539200, 700000, 800000, 345000, 56, 'http://localhost/pitch/food2.mp4', '$2y$10$N6tMWtF9FRuZOJ3lc8rc7OJ0SPnde10F2HDWStb2.ovUvxt.bZSd.'),
(10, 1, 'Nandini', 'VillageVibe foods', 'Food', 'VillageVibe Foods aims to create an immersive experience around traditional non-vegetarian dishes. Our business model revolves around providing a charming dine-in atmosphere, allowing customers to savor authentic village flavors in a rustic setting. For those who prefer enjoying our offerings at home, we offer a seamless takeout and delivery service. Additionally, we extend our reach through catering services, bringing our unique village-style cuisine to events and gatherings. To cater to the growing demand for convenience, we also offer subscription boxes, providing curated ingredients and recipes for customers to recreate the village food experience in their own homes. Embracing the digital era, our online platform facilitates easy ordering, reservations, and virtual sharing of the VillageVibe Foods experience.', 'VillageVibe Foods distinguishes itself through a unique combination of authentic flavors, rustic ambiance, and a commitment to preserving traditional non-vegetarian recipes. Our focus on sourcing high-quality, local ingredients ensures an unparalleled taste that transports customers to the heart of a village kitchen. The immersive dine-in experience captures the essence of village life, creating a distinctive atmosphere that sets us apart. Whether enjoying our offerings in-house, through takeout, or with our subscription boxes, customers can count on the genuine and delightful VillageVibe experience. Our dedication to bridging the gap between tradition and modern convenience, coupled with a passion for preserving the rich heritage of non-vegetarian cuisine, establishes VillageVibe Foods as a standout destination for those seeking an authentic and memorable culinary journey.\r\n', 'Cultural Explores, Event Organizers and Hosts , Convenience Seekers', 253700, 539200, 700000, 800000, 345000, 56, 'http://localhost/pitch/food2.mp4', '$2y$10$w5B2Qi4cQokfCZZc02tvou/LzQDnFQ3uLsm.pBSRXDy5iSuUjFOJ6'),
(11, 5, 'Monica', 'GemCraft', 'Jewellery', 'Embarking on the journey of a jewelry startup, our business model will be a critical foundation for success. Whether you choose the path of e-commerce retail, offering custom designs, subscription boxes, wholesale to retailers, dropshipping, a brick-and-mortar boutique, or collaborations, the key is aligning your model with your strengths and target audience. Crafting a unique value proposition in the competitive jewelry market is essential. Whether you focus on online sales, personalized designs, or innovative collaborations, ensure that your chosen model resonates with your brand identity and fulfills the needs and desires of your customers.\r\n', '. In the competitive landscape of the jewelry industry, our unique selling proposition (USP) lies in the exquisite fusion of artisan craftsmanship and sustainable practices. Each piece tells a story, intricately designed with a commitment to ethically sourced materials, appealing to environmentally conscious consumers seeking both beauty and conscience in their adornments. Our dedication to customization adds a personal touch, allowing customers to be active participants in the creation of their unique, one-of-a-kind pieces. By making luxury affordable, we aim to democratize elegance, offering high-quality, stylish jewelry that transcends price barriers. Our commitment to innovation ensures that our designs not only follow trends but set new ones, positioning our brand as a beacon of creativity in the jewelry landscape.', 'Lifestyle and Interests, Occasions , Values and Benefits', 199999, 275000, 384999, 562000, 175000, 68, 'http://localhost/pitch/jewellery.mp4', '$2y$10$zWKVEL6bXdkvFpnbUAgWmum4ASZO0QrXUfjXYporZngYBhhoES8K.'),
(12, 2, 'Ranjitha', 'Ethereal Adornments ', 'Jewellery', 'Consider a direct-to-consumer model where we sell our traditional earrings online. We could also explore partnerships with bridal shops or collaborate with wedding planners. Offering customization options for brides or exclusive collections for different regions can add value. Additionally, consider integrating an e-commerce platform for easy online transactions.\r\n\r\n', 'Our unique selling proposition (USP) could focus on combining traditional craftsmanship with modern design, creating timeless pieces that blend seamlessly with both traditional and contemporary wedding attire. Emphasize the cultural significance of each design and perhaps offer a personalized touch, like custom engraving or birthstone incorporation, making each pair of earrings a cherished, unique piece for brides.\r\n\r\n', 'Bride\'s to be, Engaging , Wedding', 532000, 890000, 1048001, 1258000, 540000, 57, 'http://localhost/pitch/jewel2.mp4', '$2y$10$wsL6.ESiVcOtYL69blzUJujBmAFkhQ/PGu9hNexV8uYgKAp1i5Kma'),
(13, 3, 'Savitri', 'Divine Circlets', 'Jewellery', ' Our business model for Divine Circlets could leverage the power of e-commerce, offering customers a seamless online shopping experience with a diverse range of bangle designs available for purchase. Implementing a customization service allows clients to tailor their bangles to their liking, from engravings to gemstone selections. Consider introducing bridal packages to cater specifically to brides, offering complete sets for various wedding events. Collaborations with wedding-related businesses can expand your customer base, while online consultations provide a personalized touch. A subscription service option can keep customers engaged with regular bangle deliveries. Additionally, organizing physical showrooms or pop-up events enables potential buyers to experience the elegance of Divine Circlets in person. This multi-faceted approach ensures flexibility and caters to a diverse range of customer preferences.\r\n', 'The Unique Selling Proposition (USP) for Divine Circlets lies in the fusion of timeless elegance and personalized artistry. Unlike generic bangle retailers, Divine Circlets offers a curated collection of exquisitely crafted bangles that seamlessly blend tradition with contemporary design. Our commitment to customization sets us apart, allowing customers to engrave meaningful messages, select their preferred gemstones, and choose from a variety of metals. Every Divine Circlet tells a unique story, making it not just a piece of jewelry but a cherished symbol of individuality and love. Our emphasis on quality craftsmanship, coupled with a personalized touch, ensures that each bangle becomes a bespoke masterpiece, symbolizing the divine connection between craftsmanship and the wearer\'s personal journey.\r\n', 'Designed Bangles, Traditional', 500000, 950000, 1270000, 1500000, 589000, 60, 'http://localhost/pitch/j3.mp4', '$2y$10$mAol7XIvxdbeQEbheLZU4OvM/XZO8tltVIUuXECpPsq7BdZUdw0ce');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `entry`
--
ALTER TABLE `entry`
  ADD PRIMARY KEY (`SL_NO`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `entry`
--
ALTER TABLE `entry`
  MODIFY `SL_NO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
